import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import NavBar, { Menu } from "@/components/NavBar";
import MenuIcon from "@/components/icons/Menu";
import theme from "./theme";
import { ThemeProvider } from "@mui/material/styles";
import QueryProvider from "@/components/QueryProvider";
import { AppProvider } from "./context";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Aha AI Exam2",
  description: "Generated by create next app",
};

// This may be retrieved from some BE api with user session / info
// This also can be extracted to a single routes file
export const menus: Menu[] = [
  { route: "/", label: "Home", icon: MenuIcon },
  { route: "/tags", label: "Tags", icon: MenuIcon, dot: true },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <QueryProvider>
          <ThemeProvider theme={theme}>
            <AppProvider menus={menus}>
              <div className="flex">
                <NavBar className="xs:hidden" menus={menus} />
                <div className="text-white flex-auto bg-[var(--Greyscale-BG---dark)]">
                  {children}
                </div>
              </div>
            </AppProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
